apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: application-sample
  name: component-sample
  namespace: application-service-system
spec:
  ports:
  - port: 1112
    targetPort: 1112
  selector:
    app.kubernetes.io/instance: component-sample
status:
  loadBalancer: {}
